In [ ]:
新的ndarray对象可以通过任何下列数组创建例程或使用低级ndarray构造函数构造。

In [ ]:
# numpy.empty
# 它创建指定形状和dtype的未初始化数组
numpy.empty(shape, dtype = float, order = 'C')
构造器接受下列参数：
序号	参数及描述
1.	Shape 空数组的形状，整数或整数元组
2.	Dtype 所需的输出数组类型，可选
3.	Order 'C'为按行的 C 风格数组，'F'为按列的 Fortran 风格数组

In [1]:
# numpy.empty
import numpy as np 
x = np.empty([3,2], dtype =  int)  
print (x)
# 注意：数组元素为随机值，因为它们未初始化。

[[1476243728          0]
 [1476274608          0]
 [ 429439408        400]]


In [ ]:
numpy.zeros
返回特定大小，以 0 填充的新数组。
构造器接受下列参数：
序号	参数及描述
1.	Shape 空数组的形状，整数或整数元组
2.	Dtype 所需的输出数组类型，可选
3.	Order 'C'为按行的 C 风格数组，'F'为按列的 Fortran 风格数组

In [6]:
# numpy.zeros
# 含有 5 个 0 的数组，默认类型为 float  
import numpy as np 
x = np.zeros(5)  
print (x)

[0. 0. 0. 0. 0.]


In [3]:
# 自定义类型 
import numpy as np 
x = np.zeros((2,2), dtype =  [('x',  'i4'),  ('y',  'i4')])  
print (x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [ ]:
numpy.ones
返回特定大小，以 1 填充的新数组。
numpy.ones(shape, dtype = None, order = 'C')
构造器接受下列参数：
序号	参数及描述
1.	Shape 空数组的形状，整数或整数元组
2.	Dtype 所需的输出数组类型，可选
3.	Order 'C'为按行的 C 风格数组，'F'为按列的 Fortran 风格数组

In [4]:
# 含有 5 个 1 的数组，默认类型为 float  
import numpy as np 
x = np.ones(5)  
print (x)

[1. 1. 1. 1. 1.]


In [5]:
import numpy as np 
x = np.ones([2,2], dtype =  int)  
print (x)

[[1 1]
 [1 1]]
