In [ ]:
NumPy 包包含一个 Matrix库numpy.matlib。此模块的函数返回矩阵而不是返回ndarray对象

In [ ]:
matlib.empty()
matlib.empty()函数返回一个新的矩阵，而不初始化元素。 该函数接受以下参数。
numpy.matlib.empty(shape, dtype, order)
其中：
序号	参数及描述
1.	shape 定义新矩阵形状的整数或整数元组
2.	Dtype 可选，输出的数据类型
3.	order C 或者 F

In [1]:
import numpy.matlib 
import numpy as np 
print (np.matlib.empty((2,2))  )
# 填充为随机数据

[[7.29446591e-315 7.29367872e-315]
 [9.42311741e-312 9.42222329e-312]]


In [2]:
# numpy.matlib.zeros()
# 此函数返回以零填充的矩阵。

import numpy.matlib 
import numpy as np 
print (np.matlib.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [3]:
# numpy.matlib.ones()
# 此函数返回以一填充的矩阵。

import numpy.matlib 
import numpy as np 
print (np.matlib.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [ ]:
numpy.matlib.eye()
这个函数返回一个矩阵，对角线元素为 1，其他位置为零。 该函数接受以下参数。
其中：
序号	参数及描述
1.	n 返回矩阵的行数
2.	M 返回矩阵的列数，默认为n
3.	k 对角线的索引
4.	dtype 输出的数据类型

In [4]:
import numpy.matlib 
import numpy as np 
print (np.matlib.eye(n =  3, M =  4, k =  0, dtype =  float))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [5]:
# numpy.matlib.identity()
# numpy.matlib.identity()函数返回给定大小的单位矩阵。单位矩阵是主对角线元素都为 1 的方阵。

import numpy.matlib 
import numpy as np 
print (np.matlib.identity(5, dtype =  float))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
# numpy.matlib.rand()
# numpy.matlib.rand()`函数返回给定大小的填充随机值的矩阵。

import numpy.matlib 
import numpy as np 
print (np.matlib.rand(3,3))

[[7.68843849e-01 3.64699109e-01 5.67125501e-01]
 [2.38346247e-04 7.86631661e-01 3.79862676e-01]
 [7.69341679e-01 6.53159789e-01 3.76308794e-02]]


In [7]:
import numpy.matlib 
import numpy as np  

i = np.matrix('1,2;3,4')  
print (i)

[[1 2]
 [3 4]]


In [8]:
import numpy.matlib 
import numpy as np  

j = np.asarray(i)  
print (j)

[[1 2]
 [3 4]]


In [9]:
import numpy.matlib 
import numpy as np  

k = np.asmatrix (j)  
print( k)

[[1 2]
 [3 4]]
